# CXX=g++
# CFLAGS=-g -O3 -Wall

# CPP_OUTPUT=page_rank

# all:$(CPP_OUTPUT)

# CPP_OUTPUT:page_rank.cpp table.cpp table.h
# 	$(CXX) $(CFLAGS) -o $(CPP_OUTPUT) page_rank.cpp table.cpp 
pagerank: page_rank.cpp table.cpp table.h
	g++ -O3 -Wall -o pagerank page_rank.cpp table.cpp 
